// packages/tmv/src/components/ControlsBar/pc/PC.tsx
import * as React from 'react'
import classNames from 'classnames'
import Progress from '../../Progress'
import Fullscreen from '../../FullScreen'
import Volume from '../../Volume'
import Setting from '../../Setting'
import Timer from '../../Timer'
import NextVideo from '../../NextVideo'
import PlayBtn from '../../PlayBtn'
import PlaybackRate from '../../PlaybackRate'
import Definition from '../../Definition'
import Bezel from '../../Bezel'
import Loading from '../../Loading'
import './pc.less'

class PCControl extends React.Component<any, any> {
    private timer: any
    private video: any
    constructor(props: any) {
        super(props)

        this.state = {
            visible: false,
            bezelType: '',
            isProgressSliding: false
        }

        this.timer = null
    }

    componentDidMount() {
        const { videoId } = this.props
        this.video = document.getElementById(videoId)
    }

    render() {
        const { visible, bezelType, isProgressSliding } = this.state
        const { videoId, toNextVideo, mute, qualityList = [], isLoading, isPlaying, autoPlay } = this.props

        return (
            <div
                className="tmv-controls-container"
                onMouseMove={this.handleMouseMove}
                onMouseLeave={this.handleMouseLeave}
                onClick={this.handleVideoPlay}
                onDoubleClick={this.dispatchVideoDblClick}>
                <Bezel type={bezelType} />
                {isLoading && !isProgressSliding && <Loading />}
                <div
                    className={classNames({
                        ['tmv-controls']: true,
                        ['tmv-controls-hide']: isPlaying && !visible
                    })}>
                    <div
                        className="tmv-controls-bar"
                        onClick={this.stopPropagation}
                        onDoubleClick={this.stopPropagation}>
                        <Progress videoId={videoId} onSlideStatusChange={this.changeProgressSlideStatus} />
                        <div className="tmv-controls-coms">
                            <div className="tmv-svg-btn">
                                <PlayBtn handleVideoPlay={this.handleVideoPlay} isPlaying={isPlaying} />
                            </div>

                            <div
                                className={classNames({
                                    ['tmv-svg-btn']: true,
                                    ['tmv-svg-btn-disable']: !toNextVideo
                                })}>
                                <NextVideo toNextVideo={toNextVideo} />
                            </div>

                            <Timer videoId={videoId} />
                            <div className="tmv-controls-title"></div>
                            {qualityList.length > 0 && (
                                <Definition videoId={videoId} qualityList={qualityList} autoPlay={autoPlay} />
                            )}
                            <PlaybackRate videoId={videoId} />

                            <div className="tmv-svg-btn">
                                <Volume videoId={videoId} mute={mute} />
                            </div>
                            <div className="tmv-svg-btn">
                                <Setting videoId={videoId} />
                            </div>
                            <div className="tmv-svg-btn">
                                <Fullscreen videoId={videoId} />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }

    stopPropagation = (e: any) => {
        e.stopPropagation()
    }

    dispatchVideoDblClick = () => {
        const clickEvent = document.createEvent('MouseEvents')
        clickEvent.initEvent('dblclick', true, true)
        this.video.dispatchEvent(clickEvent)
    }

    changeProgressSlideStatus = (status: string) => {
        this.setState({ isProgressSliding: status === 'start' })
    }

    handleMouseMove = () => {
        this.setState({ visible: true })

        this.clearTimer()

        this.timer = setTimeout(() => {
            this.setState({ visible: false })
            this.clearTimer()
        }, 3000)
    }

    handleMouseLeave = () => {
        this.setState({ visible: false })
        this.clearTimer()
    }

    clearTimer = () => {
        if (this.timer) {
            clearTimeout(this.timer)
            this.timer = null
        }
    }

    handleVideoPlay = () => {
        this.props.handleVideoPlay()

        this.setState({
            bezelType: this.video.paused ? 'play' : 'pause'
        })
    }
}

export default PCControl

// packages/tmv/src/components/ControlsBar/pc/PC.vue
<template>
    <div
        class="tmv-controls-container"
        @mousemove="handleMouseMove"
        @mouseleave="handleMouseLeave"
        @click="clickToPlayVideo"
        @dblclick="dispatchVideoDblClick"
    >
        <Bezel :type="bezelType" />
        <Loading v-if="isLoading && !isProgressSliding" />
        <div class="tmv-controls" :class="{ 'tmv-controls-hide': isPlaying && !visible }">
            <div class="tmv-controls-bar" @click="stopPropagation" @dblclick="stopPropagation">
                <Progress :videoId="videoId" :onSlideStatusChange="changeProgressSlideStatus" />
                <div class="tmv-controls-coms">
                    <div class="tmv-svg-btn">
                        <PlayBtn :handleVideoPlay="handleVideoPlay" :isPlaying="isPlaying" />
                    </div>

                    <div class="tmv-svg-btn" :class="{ 'tmv-svg-btn-disable': !toNextVideo }">
                        <NextVideo :toNextVideo="toNextVideo" />
                    </div>

                    <Timer :videoId="videoId" />
                    <div class="tmv-controls-title"></div>

                    <Definition
                        v-if="qualityList && qualityList.length"
                        :videoId="videoId"
                        :qualityList="qualityList"
                        :autoPlay="autoPlay"
                    />

                    <PlaybackRate :videoId="videoId" />

                    <div class="tmv-svg-btn">
                        <Volume :videoId="videoId" :mute="mute" />
                    </div>
                    <div class="tmv-svg-btn">
                        <Setting :videoId="videoId" />
                    </div>
                    <div class="tmv-svg-btn">
                        <Fullscreen :videoId="videoId" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import PlayBtn from '../../PlayBtn/index.vue'
import NextVideo from '../../NextVideo/index.vue'
import Progress from '../../Progress/index.vue'
import Timer from '../../Timer/index.vue'
import Loading from '../../Loading/index.vue'
import Bezel from '../../Bezel/index.vue'
import Fullscreen from '../../FullScreen/index.vue'
import Setting from '../../Setting/index.vue'
import Volume from '../../Volume/index.vue'
import Definition from '../../Definition/index.vue'
import PlaybackRate from '../../PlaybackRate/index.vue'

import './pc.less'

export default {
    name: 'PCControl',
    props: ['videoId', 'toNextVideo', 'handleVideoPlay', 'isPlaying', 'isLoading', 'mute', 'qualityList', 'autoPlay'],
    components: {
        PlayBtn,
        NextVideo,
        Progress,
        Timer,
        Loading,
        Bezel,
        Fullscreen,
        Setting,
        Volume,
        Definition,
        PlaybackRate
    },
    data: () => {
        return {
            bezelType: '',
            timer: null,
            video: null,
            visible: false,
            isProgressSliding: false
        }
    },
    mounted() {
        this.video = document.getElementById(this.videoId)
    },
    methods: {
        stopPropagation(e) {
            e.stopPropagation()
        },
        dispatchVideoDblClick() {
            const clickEvent = document.createEvent('MouseEvents')
            clickEvent.initEvent('dblclick', true, true)
            this.video.dispatchEvent(clickEvent)
        },

        handleMouseMove() {
            this.visible = true

            this.clearTimer()

            this.timer = setTimeout(() => {
                this.visible = false
                this.clearTimer()
            }, 3000)
        },

        handleMouseLeave() {
            this.visible = false
            this.clearTimer()
        },

        clearTimer() {
            if (this.timer) {
                clearTimeout(this.timer)
                this.timer = null
            }
        },

        clickToPlayVideo() {
            this.handleVideoPlay()
            this.bezelType = this.video.paused ? 'play' : 'pause'
        },

        changeProgressSlideStatus(status) {
            this.isProgressSliding = status === 'start'
        }
    }
}
</script>
